mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
  path('', views.index, name='index'),
  path('get_data/', views.get_data, name='get_data'),
]

mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime


# # my classes
class CarInfor(models.Model):
  # car_id = models.IntegerField(default=0)    
  car_name = models.CharField(max_length=200) 
  price = models.FloatField(default=0)       
  register_time = models.CharField(max_length=200)
  register_location = models.CharField(max_length=200)
  mileage = models.FloatField(default=0)       
  gear_box = models.CharField(max_length=200)
  owned = models.IntegerField(default=0)
  manufacturer = models.CharField(max_length=200)
  grade = models.CharField(max_length=200)
  size_x = models.FloatField(default=0)       
  size_y = models.FloatField(default=0)       
  size_z = models.FloatField(default=0)       
  wheelbase = models.FloatField(default=0)       
  weight = models.FloatField(default=0)       
  displacement = models.FloatField(default=0)       
  cylinder = models.CharField(max_length=200)
  horsepower = models.FloatField(default=0)       
  torque = models.FloatField(default=0)       
  fueltype = models.CharField(max_length=200)
  intake_form = models.CharField(max_length=200)
  oil_type = models.CharField(max_length=200)
  fuel_supply = models.CharField(max_length=200)
  emission_standard = models.CharField(max_length=200)

mysite/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, JsonResponse
from django.template import loader
from django.core.exceptions import FieldDoesNotExist

from .models import CarInfor


# Create your views here.
def index(request):
  fields = [f.name for f in CarInfor._meta.get_fields()]
  fields.remove('id')
  fields.remove('car_name')
  translate = {
    'price': '价格',
    'register_time': '上牌时间',
    'register_location': '上牌地',
    'mileage': '里程',
    'gear_box': '档位',
    'owned': '转手次数',
    'manufacturer': '制造商',
    'grade': '分级',
    'size_x': '长度 x',
    'size_y': '长度 y',
    'size_z': '长度 z',
    'wheelbase': '轴距',
    'weight': '整备重量',
    'displacement': '排量',
    'cylinder': '气缸',
    'horsepower': '马力',
    'torque': '扭矩',
    'fueltype': '燃料',
    'intake_form': '进气形式',
    'oil_type': '汽油',
    'fuel_supply': '供油方式',
    'emission_standard': '排放标准',
  }
  fields = [{'en': f, 'ch': translate[f]} for f in fields]
  context = {'carinfor_field_list': fields}
  template = loader.get_template('polls/index.html')
  return HttpResponse(template.render(context, request))

def get_data(request):
  attrib = request.GET['attrib']
  # size = request.GET['size']
  size = 50
  try:
    CarInfor._meta.get_field(attrib)
  except FieldDoesNotExist:
    raise Http404('Attrib Does Not Exist!')
  attrib_data = [x[0] for x in CarInfor.objects.values_list(attrib)]
  return JsonResponse({'data': attrib_data})

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/darkly/bootstrap.min.css" rel="stylesheet" integrity="sha384-w+yWASP3zYNxxvwoQBD5fUSc1tctKq4KUiZzxgkBSJACiUp+IbweVKvsEhMI+gz7" crossorigin="anonymous">
  
  <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.js"></script>
  <!-- load django static tag -->
  {% load static %}
  <!-- load utils.js first -->
  <script src="{% static 'polls/scripts/utils.js' %}"></script>
  <!-- load other scripts -->
  <script src="{% static 'polls/scripts/graph_checker.js' %}"></script>
  <script src="{% static 'polls/scripts/graphs_feeder.js' %}"></script>

  <title>Document</title>
</head>
<body style="height: 100vh;">
  
  <div class="jumbotron p-0" style="height: 100%;">

    <div class="header">
      <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <a class="navbar-brand" href="#">导航</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="#">主页 <span class="sr-only">(当前)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">链接</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">菜单</a>
              <div class="dropdown-menu" aria-labelledby="dropdownId">
                <a class="dropdown-item" href="#">开始</a>
                <a class="dropdown-item" href="#">结束</a>
              </div>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
          </form>
        </div>
      </nav>
    </div>

    <div class="jumbotron text-center" style="height: auto; margin-bottom: 0;">

      <div class="container">
        <!-- <h2 class="jumbptron-heading">二手车参数</h2> -->

        <div class="btn-group">
          <button type="button" class="btn btn-primary">参数 A</button>
          <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span id="dropdown-x">（空）</span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <div class="dropdown-menu dropdown-menu-right" style="height: auto; max-height: 200px; overflow-x: hidden;">
            <a href="#" class="dropdown-item" onclick="on_x_click()">（空）</a>
            {% for field in carinfor_field_list %}
              <a href="#" class="dropdown-item" onclick="on_x_click('{{ field.en }}', '{% url 'polls:get_data' %}', '{{ field.ch }}')">{{ field.ch }}</a>
            {% endfor %}
          </div>
        </div>

        <div class="btn-group">
          <button type="button" class="btn btn-primary">参数 B</button>
          <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span id="dropdown-y">（空）</span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <div class="dropdown-menu dropdown-menu-right" style="height: auto; max-height: 200px; overflow-x: hidden;">
            <a href="#" class="dropdown-item" onclick="on_y_click()">（空）</a>
            {% for field in carinfor_field_list %}
              <a href="#" class="dropdown-item" onclick="on_y_click('{{ field.en }}', '{% url 'polls:get_data' %}', '{{ field.ch }}')">{{ field.ch }}</a>
            {% endfor %}
          </div>
        </div>

        <hr>

        <div id="carouselId" class="carousel slide" data-ride="carousel">
          <!-- <ol class="carousel-indicators">
            <li data-target="#carouselId" data-slide-to="0" class="active"></li>
            <li data-target="#carouselId" data-slide-to="1"></li>
            <li data-target="#carouselId" data-slide-to="2"></li>
          </ol> -->
          <div class="carousel-inner" role="listbox" id="display-inner">
            <div class="carousel-item active">
              <canvas id="scatter-chart-canvas"></canvas>
              <!-- <div class="carousel-caption d-none d-md-block">
                <h3>Title</h3>
                <p>Description</p>
              </div> -->
            </div>
            <div class="carousel-item">
              <canvas id="bar-chart-canvas"></canvas>
              <!-- <div class="carousel-caption d-none d-md-block">
                <h3>Title</h3>
                <p>Description</p>
              </div> -->
            </div>
            <div class="carousel-item">
              <canvas id="line-chart-canvas"></canvas>
              <!-- <div class="carousel-caption d-none d-md-block">
                <h3>Title</h3>
                <p>Description</p>
              </div> -->
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselId" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselId" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

      </div>
    </div>
  </div>
</body>
</html>
<!--
{% if carinfor_field_list %}
  <ul>
  {% for field in carinfor_field_list %}
    <li>{{ field }}</li>
  {% endfor %}
  </ul>
{% else %}
  <p>No Fields Available.</p>
{% endif %} -->